version: '2'
services:
  cdippgateway-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/cdippgateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cdippgateway
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
